create table deeplink
(
    id            bigint not null primary key,
    identificatie varchar(40), -- uuid
    version       varchar(12),
    created       timestamptz default current_timestamp,
    content       jsonb
);

create unique index deeplink_identificatie on deeplink (identificatie);
create index deeplink_version on deeplink (version);
create index deeplink_created on deeplink (created);

ALTER TABLE deeplink
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME deeplink_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
        );
